### ISSUE TITLE
Should this library be used also for reproducing bugs from production?

### ISSUE THREAD

**Issue by amirc** [Optibus/playback#60]
Hi, A very cool library!
If we want to use it as an easy way to reproduce bugs in production services, is there any added value for the "output" or only for the "input"?

Thanks,
Amir.

**Comment by eitany** [comment]
In this case the input should be enough, but if you don't intercept output, the code will invoke the output function. As long that it doesn't raise an error and the code doesn't rely on the output method return value it should be ok.
